UDP Reciever merge to Main
Robotiators-888/2022Season pull request #14
Opened 2022-02-05 20:18 UTC by Spenceroni-Pepperoni

Closes #11

2022-02-05 20:30 UTC, liam-a-wms requested changes

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/BallDataPacket.java
> +
Add class documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/BallDataPacket.java
> +
Add method documentation describing the expected byte formatting.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/DataPacket.java
> +public interface DataPacket {
Add class and method documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/GenericBuffer.java
> +
Add class documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/GenericBuffer.java
> +    public GenericBuffer() {
Add constructor documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/GenericBuffer.java
> +    public synchronized void addData(DataPacket packet) {
Add method documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/GenericBuffer.java
> +    public synchronized T getData() {
Add method documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/LimelightDataPacket.java
> +public class LimelightDataPacket implements DataPacket {
Add class documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/LimelightDataPacket.java
> +    public DataPacket fromBytes(byte[] bytes) {
Add method documentation describing expected data format.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/RobotContainer.java
> +  private final UDPRecieverSubsystem m_udpsubsystem = new UDPRecieverSubsystem();
Referencing a deleted file. Delete this line.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/UDPReciever.java
> +public class UDPReciever<T extends DataPacket> extends Thread {
Add class documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/UDPReciever.java
> +    public UDPReciever(int port, Supplier<T> dataPacketConstructor, GenericBuffer<T> buf) {
Add constructor documentation.

2022-02-05 20:30 UTC, liam-a-wms commented on src/main/java/frc/robot/UDPReciever.java
>      @Override
Add method documentation.

2022-02-07 20:06 UTC, Spenceroni-Pepperoni commented
Added documentation comments and cleaned up code

2022-02-07 23:42 UTC, RC3PO-1 requested changes
Please create a folder in the robot directory, something like "UDP", and move the data packet classes, generic buffer, and UDPReciver classes into it for organization. In addition, id also like to see this run just to confirm that there is no more loop overrun errors.

2022-02-08 03:33 UTC, Spenceroni-Pepperoni commented
I tested the code on the bunnybot yesterday and I didn't end up getting overrun errors

2022-02-08 22:49 UTC, liam-a-wms approved these changes

2022-02-09 12:19 UTC, RC3PO-1 approved these changes

2022-02-09 12:19 UTC, merged