Limelight testy
Robotiators-888/2022Season pull request #44
Opened 2022-02-22 18:29 UTC by zdonal1573

2022-02-22 18:34 UTC, RC3PO-1 approved these changes
Looks good

2022-02-22 19:24 UTC, liam-a-wms commented
Rebase with `main` before proceeding.

2022-02-23 15:33 UTC, SixtyFiveOhTwo approved these changes

2022-02-24 01:08 UTC, KStet requested changes, later dismissed
Most of these are more stylistic and if you dont want to update them or have a reason not to thats fine. In general leaving stray comments or commented code that cannot actually be used can cause confusion to someone reading it.

2022-02-24 01:08 UTC, KStet commented on src/main/java/frc/robot/subsystems/Limelight.java
> +  public void toggleHeight(){
I'm not convinced toggling height vs having two separate buttons (one for auto high and one for auto low) is going to make sense on controls but this is up to whoever drivers are. But I would at least like to confirm drivers have given the ok on that layout. If they do want it as separate buttons, Id recommend maybe two indicators on whether the limelight thinks it can make the high and/or low shot instead of a toggle on which shot mode it is in? That functionality could be its own PR though if you go that direction

2022-02-24 01:08 UTC, KStet commented on src/main/java/frc/robot/subsystems/Shooter.java
> +     *
These should be deleted as your method is no longer there correct?

2022-02-24 01:08 UTC, KStet commented on src/main/java/frc/robot/RobotContainer.java
>                  //L_button2 auto aim and shoot
Please fix this to say L_button3 or delete it and delete the following commented out line as I believe that AutoShoot is now autoShoot so there is no reason to keep it (and potentially have someone comment it back in)?

2022-02-24 01:09 UTC, KStet commented on src/main/java/frc/robot/subsystems/Limelight.java
> +  public void toggleHeight(){
This does not have to be modified right now I meant it more as a general comment

2022-02-24 01:19 UTC, KevinH45 approved these changes

2022-02-24 12:45 UTC, RC3PO-1 commented on src/main/java/frc/robot/subsystems/Limelight.java
> +  public void toggleHeight(){
definitely can be readjusted, we checked with colin when we made this and he said it was fine.

2022-02-24 12:54 UTC, RC3PO-1 approved these changes

2022-02-26 14:19 UTC, merged